# Generated by Django 2.1.7 on 2019-03-11 17:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Hospital', 'Hospital'), ('College', 'College'), ('Hotel', 'Hotel'), ('Restaurants', 'Restaurants'), ('Movies', 'Movies')], max_length=10)),
                ('name', models.CharField(default='', max_length=30)),
                ('title', models.CharField(default='', max_length=30)),
                ('review', models.CharField(default='', max_length=100)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(blank=True, upload_to='gr-ph')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(default='', max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
