# Generated by Django 2.1.7 on 2019-03-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bang',
            name='location',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='bang',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bang',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
