# Generated by Django 2.1.7 on 2019-03-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190318_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat',
            field=models.CharField(choices=[('Hospital', 'Hospital'), ('College', 'College'), ('Hotel', 'Hotel'), ('Restaurants', 'Restaurants'), ('Movies', 'Movies')], max_length=20),
        ),
    ]
