# Generated by Django 2.1.7 on 2019-03-18 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20190318_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bang',
            name='category',
        ),
        migrations.AddField(
            model_name='bang',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Category'),
        ),
    ]
