# Generated by Django 2.1.7 on 2019-03-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20190318_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imgg',
            field=models.ImageField(blank=True, upload_to='cat_pic'),
        ),
    ]
