# Generated by Django 2.1.7 on 2019-03-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_category_imgg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bang',
            name='image',
        ),
    ]
