# Generated by Django 2.1.7 on 2019-03-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoounts', '0004_auto_20190304_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
