# Generated by Django 2.1.7 on 2019-03-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acoounts', '0005_objectd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Objectd',
        ),
    ]
